name: golden_price
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+14

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  provider: ^6.1.5
  dio: ^5.8.0+1
  get_it: ^8.0.3
  alice:
    git:
      url: https://github.com/taufiqjack/alice_new
      ref: master
  flutter_dotenv: ^6.0.0
  freezed_annotation: ^3.0.0
  flutter_bloc: ^9.1.1
  build_runner: ^2.4.13
  freezed: ^3.0.6
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  rflutter_alert: ^2.0.7
  awesome_dialog_plus: ^3.2.3
  page_transition: ^2.2.1
  responsive_framework: ^1.5.1
  skeleton_text: ^3.0.1
  flutter_launcher_icons: ^0.14.3
  fl_chart: ^1.0.0
  internet_connection_checker_plus: ^2.7.2
  google_mobile_ads: ^6.0.0
  hijriyah_indonesia: ^0.1.7
  firebase_core: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - .env
